#%RAML 1.0 Trait
usage: Use this trait for resources whose response body is a single item
responses:
    200:
      body:
        application/json:
          type: <<typeName>>
          example: !include /examples/<<typeName>>.json
