package com.baeldung.mongodb;

import com.baeldung.mongodb.daos.UserRepository;
import com.baeldung.mongodb.models.User;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.List;


@RunWith(SpringRunner.class)
public class MongoDbAutoGeneratedFieldIntegrationTest {

    @Autowired
    private UserRepository userRepository;

    @Test
    public void contextLoads() {}

    @Test
    public void givenUserObject_whenSave_thenCreateNewUser() {

        User user = new User();
        user.setFirstName("John");
        user.setLastName("Doe");
        user.setEmail("john.doe@example.com");
        userRepository.save(user);

        List<User> storedUsers = userRepository.findAll();
        storedUsers.forEach(System.out::println);
    }


}
