java_sources(
    dependencies=[
        "src/resources/com/baeldung/hellopant:word",
    ],
)



deploy_jar(
    name="HelloPant",
    main="com.baeldung.hellopant",
    dependencies=[
        ":hellopant",
    ],
)
