spring.application.name=mcp-logging-demo-client

spring.main.web-application-type=none

spring.main.banner-mode=off

logging.file.name=target/mcp-logging-demo-client.log

spring.ai.mcp.client.type=SYNC

spring.autoconfigure.exclude=org.springframework.ai.mcp.server.common.autoconfigure.ToolCallbackConverterAutoConfiguration

spring.ai.mcp.client.stdio.connections.password-strength-logging-server.command=java

spring.ai.mcp.client.stdio.connections.password-strength-logging-server.args=-Dloader.main=com.baeldung.mcp.logging.server.McpLoggingServerApplication,-jar,${MCP_JAR:target/spring-ai-mcp-logging.jar},--spring.profiles.active=server

spring.autoconfigure.exclude=org.springframework.ai.model.anthropic.autoconfigure.AnthropicChatAutoConfiguration