###
# Create a new order
POST http://localhost:8080/order
Content-Type: application/json

{ 
  "order" : {
    "orderId": "9c7e2b84-3f5a-4d8e-9a1c-7b2f6e3d1a9b",
    "items": [
      {
        "quantity": 1,
        "sku": "sku1"
      },
      {
        "quantity": 3,
        "sku": "sku2"
      }
    ]
  },
  "billingInfo" : {
    "cardToken": "XXXX12349812981723",
    "amount": 500.00,
    "currency": "USD"
  },
  "shippingInfo": {
    "shipTo": "Misty Shadowlight",
    "addrLine1": "123, Mistway Path",
    "addrLine2": "Eldoria Valley",
    "city": "Luminara",
    "countryCode": "ARV",
    "postalCode": "472-FE-LU",
    "deliveryInstructions": "Please ring the bell"
  },
  "customer" : {
    "name": "Max Ludenwall",
    "uuid": "f3a9c1e2-7b4d-4c9e-9f1a-2d8e6b5a3c7f",
    "birthDate": "1970-01-01"
  }
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });

    client.global.set("orderExecutionId", response.body.orderExecutionId);
    console.log("Order created with ID: " + response.body.orderExecutionId);

%}

###
# Check payment status
GET http://localhost:8080/order/{{orderExecutionId}}/payment

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("transactionId", response.body.transactionId);
    console.log("Payment TransactionId: " + response.body.transactionId);
%}

###
# Update payment status
PUT http://localhost:8080/order/{{orderExecutionId}}/paymentStatus
Content-Type: application/json

{
  "status": "APPROVED",
  "transactionId": "{{transactionId}}",
  "authorizationId": "auth1234",
  "cause": null
}

###
# Update payment status
PUT http://localhost:8080/order/{{orderExecutionId}}/shippingStatus
Content-Type: application/json

{
  "status": "SHIPPED",
  "statusTime" : "2025-11-11T14:30:04.000Z"
}

###
# Update payment status
PUT http://localhost:8080/order/{{orderExecutionId}}/shippingStatus
Content-Type: application/json

{
  "status": "DELIVERED",
  "statusTime" : "2025-11-11T18:30:04.000Z"
}
