package com.baeldung.mongodb.daos;

import org.springframework.data.mongodb.repository.MongoRepository;

import com.baeldung.mongodb.models.UserAutoGeneratedField;


public interface UserAutoGeneratedFieldRepository extends MongoRepository<UserAutoGeneratedField, Long> {

}
