--CREATE SCHEMA IF NOT EXISTS eventuate AUTHORIZATION sa;

drop table if exists message;

CREATE TABLE message (
  ID VARCHAR(100) PRIMARY KEY,
  DESTINATION VARCHAR(1000) NOT NULL,
  HEADERS VARCHAR(1000) NOT NULL,
  PAYLOAD VARCHAR(1000) NOT NULL,
  MESSAGE_PARTITION SMALLINT,
  CREATION_TIME BIGINT,
  PUBLISHED BIGINT
);

