CREATE TABLE IF NOT EXISTS book (name VARCHAR,author VARCHAR,isbn VARCHAR(13) PRIMARY KEY);
CREATE TABLE IF NOT EXISTS catalog (isbn VARCHAR(13) FOREIGN KEY REFERENCES book(isbn), numberOfItems INT);

