### OAuth2 Client Credentials Grant Request for Tenant 1
POST http://localhost:8080/tenants/issuer1/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Y2xpZW50MTpzZWNyZXQx

grant_type=client_credentials&
scope=account:read

###