DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (

  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,

);

INSERT INTO EMPLOYEE (ID, NAME) VALUES (10, 'EMP 10');
INSERT INTO EMPLOYEE (ID, NAME) VALUES (20, 'EMP 20');
