#%RAML 1.0
title: OrgMgmt
version: V1
baseUri: http://localhost:8080/api

/companies:
 displayName: Companies
 /{username}:
   uriParameters:
     username:
       type: string
       required: true
       example: abirkhan
   get:
       description: get the company names from collection.
       queryParameters:
         city:
           type: string
           required: false
           example: Dhaka
       responses:
         200:
           body:
             application/json:
               example: |
                 [{
                 "id": 1,
                 "name": "Baeldung",
                 "username": "test",
                 "email": "test@baeldung.com",
                 "address": {
                   "street": "Kulas Light",
                   "suite": "Apt. 556",
                   "city": "Gwenborough",
                   "zipcode": "92998-3874",
                   "geo": {
                     "lat": "-37.3159",
                     "lng": "81.1496"
                   }
                 },
                 "phone": "1-343-737473-83483",
                 "website": "baeldung.com",
                 "company": {
                   "name": "Baeldung blog",
                   "catchPhrase": "Nothing ",
                   "bs": "harness real-time e-markets"
                  } }]