CREATE TABLESPACE JPA DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\JPA.DBF' SIZE 100M AUTOEXTEND ON MAXSIZE 2048M;

--DROP USER JPA CASCADE;
CREATE USER JPA IDENTIFIED BY JPA DEFAULT TABLESPACE JPA;
ALTER USER JPA QUOTA UNLIMITED ON "JPA" ACCOUNT UNLOCK;

GRANT CREATE SESSION TO "JPA";
GRANT ALTER SESSION TO "JPA";
GRANT CREATE TABLE TO "JPA";
GRANT CREATE TRIGGER TO "JPA";
GRANT CREATE VIEW TO "JPA";
GRANT CREATE DIMENSION TO "JPA";
GRANT CREATE CLUSTER TO "JPA";
GRANT CREATE INDEXTYPE TO "JPA";
GRANT CREATE ROLE TO "JPA";
GRANT CREATE SEQUENCE TO "JPA";
GRANT CREATE TYPE TO "JPA";
GRANT CREATE MATERIALIZED VIEW TO "JPA";
GRANT CREATE PROCEDURE TO "JPA";
GRANT CREATE SYNONYM TO "JPA";

CREATE SEQUENCE SEQ_CAR_ID INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999 MINVALUE 1;

CREATE TABLE CAR
(
  ID NUMBER NOT NULL,
  MODEL VARCHAR2(50) NOT NULL,
  YEAR NUMBER(4) NOT NULL
);

ALTER TABLE CAR ADD CONSTRAINT CAR_PK PRIMARY KEY ( ID );

commit;

