@startuml
'https://plantuml.com/class-diagram

interface JdbcConnectionDetails {
   +getUsername():String
   +getPassword():String
   +getJdbcUrl():String
}
class PostgresConnectionDetails {
   +getUsername():String
   +getPassword():String
   +getJdbcUrl():String
}
class VaultAdapter {
   +getSecret(String secretKey):String
}
class JdbcConnectonDetailsConfiguration {
    +getPostgresConnection():JdbcConnectionDetails
}
PostgresConnectionDetails -left-> VaultAdapter:uses
PostgresConnectionDetails -right-|> JdbcConnectionDetails : implements
JdbcConnectonDetailsConfiguration -up-> PostgresConnectionDetails:uses


@enduml