@startuml
'https://plantuml.com/class-diagram

interface KafkaConnectionDetails {
   +getBootstrapServers():List<String>
}
class CustomKafkaConnectionDetails {
+getBootstrapServers():List<String>
}
class VaultAdapter {
   +getSecret(String secretKey):String
}
class CustomKafkaConnectionDetailsConfiguration {
    +getKafkaConnectionDetails():KafkaConnectionDetails
}
CustomKafkaConnectionDetails -left-> VaultAdapter:uses
CustomKafkaConnectionDetails -right-|> KafkaConnectionDetails:implements
CustomKafkaConnectionDetailsConfiguration -up-> CustomKafkaConnectionDetails:uses


@enduml