CREATE TABLE STUDENT (
  id INT PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE STUDENTRESULT(
subject VARCHAR(250) NOT NULL,
marks NUMERIC(8,2),
id VARCHAR(250),
FOREIGN KEY (id) references STUDENT(id)
);