#%RAML 1.0 Overlay
# File located at (archivo situado en):
# /overlays/es_ES/documentationItems.raml
masterRef: /api.raml
usage: |
  To provide user documentation and other descriptive text in Spanish
  (Para proporcionar la documentación del usuario y otro texto descriptivo en español)
title: API para servicios REST utilizados en los tutoriales RAML en Baeldung.com
documentation:
  - title: Descripción general
  - content: |
      Este documento define la interfaz para los servicios REST
      utilizados en la popular serie de RAML Tutorial en Baeldung.com
  - title: Renuncia
  - content: |
      Todos los nombres usados ​​en esta definición son pura ficción.
      Cualquier similitud entre los nombres utilizados en este tutorial
      y los de las personas reales, ya sea vivo o muerto,
      no son más que coincidenta.

  - title: Derechos de autor
  - content: |
      Derechos de autor 2016 por Baeldung.com. Todos los derechos reservados.
