#Updated keystore
#Sun May 17 12:27:51 CEST 2026
codename1.android.keystore=
codename1.android.keystoreAlias=androidKey
codename1.android.keystorePassword=password
codename1.arg.and.themeMode=modern
codename1.arg.android.keyboardOpen=true
codename1.arg.ios.newStorageLocation=true
codename1.arg.ios.themeMode=modern
codename1.arg.java.version=17
codename1.arg.javascript.inject_proxy=false
codename1.arg.nativeTheme=modern
codename1.cssTheme=true
codename1.displayName=DailyRoutine
codename1.icon=icon.png
codename1.ios.appid=Q5GHSKAL2F.com.baeldung.cn1tutorial
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=
codename1.ios.debug.certificatePassword=
codename1.ios.debug.provision=
codename1.ios.provision=
codename1.ios.release.certificate=
codename1.ios.release.certificatePassword=
codename1.ios.release.provision=
codename1.kotlin=false
codename1.mainName=DailyRoutine
codename1.packageName=com.baeldung.cn1tutorial
codename1.secondaryTitle=Baeldung Tutorial on CN1
codename1.vendor=CodenameOne
codename1.version=1.0
