
package com.baeldung.jaxws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EmployeeNotFound", targetNamespace = "http://bottomup.server.jaxws.baeldung.com/")
public class EmployeeNotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EmployeeNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EmployeeNotFound_Exception(String message, EmployeeNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EmployeeNotFound_Exception(String message, EmployeeNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.baeldung.jaxws.client.EmployeeNotFound
     */
    public EmployeeNotFound getFaultInfo() {
        return faultInfo;
    }

}
