/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baeldung_jni_RegisterNativesHelloWorldJNI */

#ifndef _Included_com_baeldung_jni_RegisterNativesHelloWorldJNI
#define _Included_com_baeldung_jni_RegisterNativesHelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baeldung_jni_RegisterNativesHelloWorldJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baeldung_jni_RegisterNativesHelloWorldJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_baeldung_jni_RegisterNativesHelloWorldJNI
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baeldung_jni_RegisterNativesHelloWorldJNI_register
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
