INSERT INTO USR.USER(NAME, EMAIL, STATUS) VALUES ('Test 1', 'test1@test.com', 'ACTIVE');
INSERT INTO USR.USER(NAME, EMAIL, STATUS) VALUES ('Test 2', 'test2@test.com', 'INACTIVE');
INSERT INTO USR.USER(NAME, EMAIL, STATUS) VALUES ('Test 3', 'test3@test.com', 'INACTIVE');
INSERT INTO USR.USER(NAME, EMAIL, STATUS) VALUES ('Test 4', 'test4@test.com', 'INACTIVE');
INSERT INTO USR.USER(NAME, EMAIL, STATUS) VALUES ('Test 5', 'test5@test.com', 'ACTIVE');