DROP TABLE IF EXISTS ARTICLE;

CREATE TABLE ARTICLE
(
    ID      INT AUTO_INCREMENT PRIMARY KEY,
    NAME    VARCHAR(64) NOT NULL,
    EDITOR  VARCHAR(64) NOT NULL,
    CONTENT MEDIUMTEXT  NOT NULL
);

INSERT INTO ARTICLE(NAME, EDITOR, CONTENT)
VALUES ('Hello World', 'Jose Anibal', '<h1>Hello World!</h1>');