spring.application.name=apache-seata-c

spring.datasource.generate-unique-name=false
spring.datasource.url=jdbc:postgresql://postgres:5432/seata
spring.datasource.username=seata
spring.datasource.password=seata
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8083

seata.enabled=true
seata.application-id=${spring.application.name}
seata.tx-service-group=my_tx_group

seata.registry.type=file
seata.registry.file.name=seata.conf

seata.config.type=file
seata.config.file.name=seata.conf

seata.service.vgroup-mapping.my_tx_group=default
seata.service.grouplist.default=seata-server:8091

seata.data-source-proxy-mode=AT
seata.enable-auto-data-source-proxy=true
