spring:
  security:
    user:
      name: user
      password: "{noop}password"
    oauth2:
      authorizationserver:
        client:
          client1:
            require-proof-key: false
            registration:
              client-name: Client 1 - Issuer 1
              client-id: client1
              client-secret: "{noop}secret1"
              client-authentication-methods:
                - client_secret_basic
              redirect-uris:
                - http://localhost:9090/login/oauth2/code/issuer1client1
              authorization-grant-types:
                - client_credentials
                - authorization_code
                - refresh_token
              scopes:
                - openid
                - email
  web:
    error:
      include-message: always
      include-exception: true
      include-stacktrace: always

