CREATE TABLE EMPLOYEE
(id BIGINT,
 name VARCHAR(10));

INSERT INTO EMPLOYEE VALUES (1, 'JOHN');
INSERT INTO EMPLOYEE VALUES (2, 'MARY');
INSERT INTO EMPLOYEE VALUES (3, 'FRANK');

CREATE TABLE SCHEDULE_DAYS
(id IDENTITY,
 employeeId BIGINT,
 dayOfWeek  VARCHAR(10));

INSERT INTO SCHEDULE_DAYS (employeeId, dayOfWeek) VALUES (1, 'FRIDAY');
INSERT INTO SCHEDULE_DAYS (employeeId, dayOfWeek) VALUES (2, 'SATURDAY');
INSERT INTO SCHEDULE_DAYS (employeeId, dayOfWeek) VALUES (3, 'MONDAY');
INSERT INTO SCHEDULE_DAYS (employeeId, dayOfWeek) VALUES (3, 'FRIDAY');

CREATE TABLE COURSE
(id BIGINT,
 name VARCHAR(10));