package com.baeldung

import com.baeldung.model.Beatle;


query whichBeatle(String lastName, String instrument) 
  Beatle(lastName, instrument;)
  or 
  (Beatle(lastName, null;) 
    and 
   whichBeatle(null, instrument;)) //recursive call to the function that allows to search in a derivation tree structure
end

rule "Ringo"
  when
    String(this == "Ringo")
    whichBeatle("Starr", "drums";)
  then
    System.out.println("The beatle is Ringo Starr");
end

rule "Paul"
  when
    String(this == "Paul")
    whichBeatle("McCartney", "bass";)
  then
    System.out.println("The beatle is Paul McCartney");
end

rule "John"
  when
    String(this == "John")
    whichBeatle("Lennon", "guitar";)
  then
    System.out.println("The beatle is John Lennon");
end

rule "George"
  when
    String(this == "George")
    whichBeatle("Harrison", "guitar";)
  then
    System.out.println("The beatle is George Harrison");
end
