@startuml
'https://plantuml.com/class-diagram
hide empty attributes
skinparam Handwritten false
skinparam ClassBorderColor black
skinparam BackgroundColor #fffce8/#f8f9fa
skinparam class {
 ArrowColor SeaGreen
 BackgroundColor #fffce8
}

class MilvusClientV2 {
   +insert(InsertReq)::InsertResp
}

class InsertReq {
   +builder()
}

class InsertResp {
   +getInsertCnt()
}

class InsertReqBuilder {
   collectionName()
   data(List<JSONObject>)
   build()
}

InsertReqBuilder -up-+ InsertReq: contains
MilvusClientV2 -right-> InsertReq: uses
MilvusClientV2 -up-> InsertResp: uses
@enduml