<!DOCTYPE html>
<html lang="en">

<head>
  <title>Invoice #$invoice.customer.firstName$</title>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, shrink-to-fit=no" />
  <link href="../../../resources/invoice.css" rel="stylesheet" />
</head>

<body>

<header>
  <h1>INVOICE</h1>
  <h2>Baeldung – The Spring Resource</h2>
</header>


<footer>
  <p>
    <em>Baeldung – The Spring Resource | Java, Spring and Web Development tutorials</em>
  </p>
  <p>
    <a href="http://baeldung.com">baeldung.com</a> | <a href="mailto:email@baeldung.com">email@baeldung.com</a>
  </p>
</footer>

</body>

</html>
