package com.baeldung.hexagonal.architecture.holiday.core.service;

import java.time.LocalDateTime;
import java.util.UUID;

public interface HolidayService {

    /**
     * @param uuid - id of the employee
     * @param from - date from
     * @param to   - date to
     * @param type - type of the vacation
     * @return - order id
     */
    UUID submitHolidayApplication(UUID uuid, LocalDateTime from, LocalDateTime to, String type);

    /**
     * @param applicationId - id of the vacation request generated by system
     */
    void acceptHoliday(UUID applicationId);

    /**
     * @param applicationId - id of the vacation request generated by system
     */
    void rejectHoliday(UUID applicationId, String reason);
}
