/**
 * This class is generated by jOOQ
 */
package com.baeldung.jooq.introduction.db.public_.tables.records;


import com.baeldung.jooq.introduction.db.public_.tables.AuthorBook;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorBookRecord extends UpdatableRecordImpl<AuthorBookRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = -1057354033;

	/**
	 * Setter for <code>PUBLIC.AUTHOR_BOOK.AUTHOR_ID</code>.
	 */
	public void setAuthorId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.AUTHOR_BOOK.AUTHOR_ID</code>.
	 */
	public Integer getAuthorId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.AUTHOR_BOOK.BOOK_ID</code>.
	 */
	public void setBookId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.AUTHOR_BOOK.BOOK_ID</code>.
	 */
	public Integer getBookId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AuthorBook.AUTHOR_BOOK.AUTHOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return AuthorBook.AUTHOR_BOOK.BOOK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getAuthorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getBookId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorBookRecord value1(Integer value) {
		setAuthorId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorBookRecord value2(Integer value) {
		setBookId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuthorBookRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AuthorBookRecord
	 */
	public AuthorBookRecord() {
		super(AuthorBook.AUTHOR_BOOK);
	}

	/**
	 * Create a detached, initialised AuthorBookRecord
	 */
	public AuthorBookRecord(Integer authorId, Integer bookId) {
		super(AuthorBook.AUTHOR_BOOK);

		setValue(0, authorId);
		setValue(1, bookId);
	}
}
