/**
 * This class is generated by jOOQ
 */
package com.baeldung.jooq.introduction.db.information_schema.tables;


import com.baeldung.jooq.introduction.db.information_schema.InformationSchema;
import com.baeldung.jooq.introduction.db.information_schema.tables.records.HelpRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Help extends TableImpl<HelpRecord> {

	private static final long serialVersionUID = 1402170374;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA.HELP</code>
	 */
	public static final Help HELP = new Help();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<HelpRecord> getRecordType() {
		return HelpRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.HELP.ID</code>.
	 */
	public final TableField<HelpRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.HELP.SECTION</code>.
	 */
	public final TableField<HelpRecord, String> SECTION = createField("SECTION", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.HELP.TOPIC</code>.
	 */
	public final TableField<HelpRecord, String> TOPIC = createField("TOPIC", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.HELP.SYNTAX</code>.
	 */
	public final TableField<HelpRecord, String> SYNTAX = createField("SYNTAX", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.HELP.TEXT</code>.
	 */
	public final TableField<HelpRecord, String> TEXT = createField("TEXT", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.HELP</code> table reference
	 */
	public Help() {
		this("HELP", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.HELP</code> table reference
	 */
	public Help(String alias) {
		this(alias, HELP);
	}

	private Help(String alias, Table<HelpRecord> aliased) {
		this(alias, aliased, null);
	}

	private Help(String alias, Table<HelpRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Help as(String alias) {
		return new Help(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Help rename(String name) {
		return new Help(name, null);
	}
}
