/**
 * This class is generated by jOOQ
 */
package com.baeldung.jooq.introduction.db.information_schema.tables;


import com.baeldung.jooq.introduction.db.information_schema.InformationSchema;
import com.baeldung.jooq.introduction.db.information_schema.tables.records.InDoubtRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InDoubt extends TableImpl<InDoubtRecord> {

	private static final long serialVersionUID = 284524946;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA.IN_DOUBT</code>
	 */
	public static final InDoubt IN_DOUBT = new InDoubt();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<InDoubtRecord> getRecordType() {
		return InDoubtRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.IN_DOUBT.TRANSACTION</code>.
	 */
	public final TableField<InDoubtRecord, String> TRANSACTION = createField("TRANSACTION", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.IN_DOUBT.STATE</code>.
	 */
	public final TableField<InDoubtRecord, String> STATE = createField("STATE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.IN_DOUBT</code> table reference
	 */
	public InDoubt() {
		this("IN_DOUBT", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.IN_DOUBT</code> table reference
	 */
	public InDoubt(String alias) {
		this(alias, IN_DOUBT);
	}

	private InDoubt(String alias, Table<InDoubtRecord> aliased) {
		this(alias, aliased, null);
	}

	private InDoubt(String alias, Table<InDoubtRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public InDoubt as(String alias) {
		return new InDoubt(alias, this);
	}

	/**
	 * Rename this table
	 */
	public InDoubt rename(String name) {
		return new InDoubt(name, null);
	}
}
