/**
 * This class is generated by jOOQ
 */
package com.baeldung.jooq.introduction.db.information_schema.tables;


import com.baeldung.jooq.introduction.db.information_schema.InformationSchema;
import com.baeldung.jooq.introduction.db.information_schema.tables.records.RightsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rights extends TableImpl<RightsRecord> {

	private static final long serialVersionUID = -2076280081;

	/**
	 * The reference instance of <code>INFORMATION_SCHEMA.RIGHTS</code>
	 */
	public static final Rights RIGHTS = new Rights();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RightsRecord> getRecordType() {
		return RightsRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.GRANTEE</code>.
	 */
	public final TableField<RightsRecord, String> GRANTEE = createField("GRANTEE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.GRANTEETYPE</code>.
	 */
	public final TableField<RightsRecord, String> GRANTEETYPE = createField("GRANTEETYPE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.GRANTEDROLE</code>.
	 */
	public final TableField<RightsRecord, String> GRANTEDROLE = createField("GRANTEDROLE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.RIGHTS</code>.
	 */
	public final TableField<RightsRecord, String> RIGHTS_ = createField("RIGHTS", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.TABLE_SCHEMA</code>.
	 */
	public final TableField<RightsRecord, String> TABLE_SCHEMA = createField("TABLE_SCHEMA", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.TABLE_NAME</code>.
	 */
	public final TableField<RightsRecord, String> TABLE_NAME = createField("TABLE_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.ID</code>.
	 */
	public final TableField<RightsRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.RIGHTS</code> table reference
	 */
	public Rights() {
		this("RIGHTS", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.RIGHTS</code> table reference
	 */
	public Rights(String alias) {
		this(alias, RIGHTS);
	}

	private Rights(String alias, Table<RightsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Rights(String alias, Table<RightsRecord> aliased, Field<?>[] parameters) {
		super(alias, InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Rights as(String alias) {
		return new Rights(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Rights rename(String name) {
		return new Rights(name, null);
	}
}
