package com.baeldung.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.baeldung.cayenne.Department;

/**
 * Class _Employee was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Employee extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String EMP_ID_PK_COLUMN = "emp_id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<Department> DEPARTMENT = Property.create("department", Department.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setDepartment(Department department) {
        setToOneTarget("department", department, true);
    }

    public Department getDepartment() {
        return (Department)readProperty("department");
    }


}
