// Generated by jextract

package foreign.c;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$14 {

    static final FunctionDescriptor _fcloseall$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle _fcloseall$MH = RuntimeHelper.downcallHandle(
        "_fcloseall",
        constants$14._fcloseall$FUNC
    );
    static final FunctionDescriptor _fsopen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _fsopen$MH = RuntimeHelper.downcallHandle(
        "_fsopen",
        constants$14._fsopen$FUNC
    );
    static final FunctionDescriptor __mingw_get_output_format$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle __mingw_get_output_format$MH = RuntimeHelper.downcallHandle(
        "__mingw_get_output_format",
        constants$14.__mingw_get_output_format$FUNC
    );
    static final FunctionDescriptor __mingw_set_output_format$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __mingw_set_output_format$MH = RuntimeHelper.downcallHandle(
        "__mingw_set_output_format",
        constants$14.__mingw_set_output_format$FUNC
    );
    static final FunctionDescriptor __mingw_get_printf_count_output$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle __mingw_get_printf_count_output$MH = RuntimeHelper.downcallHandle(
        "__mingw_get_printf_count_output",
        constants$14.__mingw_get_printf_count_output$FUNC
    );
    static final FunctionDescriptor __mingw_set_printf_count_output$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle __mingw_set_printf_count_output$MH = RuntimeHelper.downcallHandle(
        "__mingw_set_printf_count_output",
        constants$14.__mingw_set_printf_count_output$FUNC
    );
}


