// Generated by jextract

package foreign.c;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$13 {

    static final FunctionDescriptor pclose$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pclose$MH = RuntimeHelper.downcallHandle(
        "pclose",
        constants$13.pclose$FUNC
    );
    static final FunctionDescriptor _flushall$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle _flushall$MH = RuntimeHelper.downcallHandle(
        "_flushall",
        constants$13._flushall$FUNC
    );
    static final FunctionDescriptor _fgetchar$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle _fgetchar$MH = RuntimeHelper.downcallHandle(
        "_fgetchar",
        constants$13._fgetchar$FUNC
    );
    static final FunctionDescriptor _fputchar$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle _fputchar$MH = RuntimeHelper.downcallHandle(
        "_fputchar",
        constants$13._fputchar$FUNC
    );
    static final FunctionDescriptor _fdopen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fdopen$MH = RuntimeHelper.downcallHandle(
        "_fdopen",
        constants$13._fdopen$FUNC
    );
    static final FunctionDescriptor _fileno$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _fileno$MH = RuntimeHelper.downcallHandle(
        "_fileno",
        constants$13._fileno$FUNC
    );
}


