// Generated by jextract

package foreign.c;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$3 {

    static final FunctionDescriptor __mingw_printf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __mingw_printf$MH = RuntimeHelper.downcallHandleVariadic(
        "__mingw_printf",
        constants$3.__mingw_printf$FUNC
    );
    static final FunctionDescriptor __mingw_sprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __mingw_sprintf$MH = RuntimeHelper.downcallHandleVariadic(
        "__mingw_sprintf",
        constants$3.__mingw_sprintf$FUNC
    );
    static final FunctionDescriptor __mingw_snprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __mingw_snprintf$MH = RuntimeHelper.downcallHandleVariadic(
        "__mingw_snprintf",
        constants$3.__mingw_snprintf$FUNC
    );
    static final FunctionDescriptor __mingw_vfprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __mingw_vfprintf$MH = RuntimeHelper.downcallHandle(
        "__mingw_vfprintf",
        constants$3.__mingw_vfprintf$FUNC
    );
    static final FunctionDescriptor __mingw_vprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __mingw_vprintf$MH = RuntimeHelper.downcallHandle(
        "__mingw_vprintf",
        constants$3.__mingw_vprintf$FUNC
    );
    static final FunctionDescriptor __mingw_vsprintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __mingw_vsprintf$MH = RuntimeHelper.downcallHandle(
        "__mingw_vsprintf",
        constants$3.__mingw_vsprintf$FUNC
    );
}


