@startuml
'https://plantuml.com/class-diagram

interface CassandraConnectionDetails {
   +getUsername():String
   +getPassword():String
   +getContactPoints():List<Node>
   +getLocalDatacenter():String
}
class CustomCassandraConnectionDetails {
   +getUsername():String
   +getPassword():String
   +getContactPoints():List<Node>
   +getLocalDatacenter():String
}
class VaultAdapter {
   +getSecret(String secretKey):String
}
class CustomCassandraConnectionDetailsConfiguration {
    +getCustomCassandraConnectionDetails():CassandraConnectionDetails
}
CustomCassandraConnectionDetails -left-> VaultAdapter:uses
CustomCassandraConnectionDetails -right-|> CassandraConnectionDetails : implements
CustomCassandraConnectionDetailsConfiguration -up-> CustomCassandraConnectionDetails:uses


@enduml