@startuml
'https://plantuml.com/class-diagram

class SilverJobCard {
 -Object jobType
 +setJobType(Class jobTypeClass);
 +startJob();
}

class MaintenanceJob {
 +getJobType();
}
class RepairJob {
 +getJobType();
}
SilverJobCard -left-> MaintenanceJob:creates
SilverJobCard -right-> RepairJob:creates


@enduml