CREATE TABLE IF NOT EXISTS AUTHOR(
    ID BIGSERIAL PRIMARY KEY,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOK(
    ID BIGSERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL  REFERENCES AUTHOR(ID)
);

CREATE TABLE IF NOT EXISTS PAGE(
    ID BIGSERIAL PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    NUMBER BIGINT NOT NULL,
    BOOK_ID BIGINT NOT NULL REFERENCES BOOK(ID)
);

INSERT INTO AUTHOR VALUES (1, 'Donald', 'Knuth');