package com.baeldung.hexagonal.web;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;
import org.glassfish.hk2.api.Factory;

/** Creates and configures a Jackson {@link ObjectMapper} for use throughout the application */
public final class ObjectMapperFactory implements Factory<ObjectMapper> {

    /**
     * {@inheritDoc}
     *
     * <p>Configures an ObjectMapper to ignore unknown properties and to use parameter name
     * information generated by javac when deserializing JSON
     */
    @Override
    public ObjectMapper provide() {
        return new ObjectMapper().configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
            .registerModule(new ParameterNamesModule());
    }

    /**
     * {@inheritDoc}
     *
     * <p>nop
     */
    @Override
    public void dispose(final ObjectMapper instance) {
    }
}
