spring.flyway.enabled=false

spring.sql.init.platform=h2
spring.datasource.url=jdbc:h2:mem:assets;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
spring.datasource.driver-class-name=org.h2.Driver

causeway.persistence.schema.create-schema-sql-template=CREATE SCHEMA IF NOT EXISTS %s
causeway.persistence.schema.auto-create-schemas=assets

eclipselink.deploy-on-startup=true
eclipselink.ddl-generation.output-mode=database
eclipselink.ddl-generation=create-tables
eclipselink.jpa.upper-case-column-names=false
